# Generated by Django 2.2.7 on 2019-11-16 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitboi_photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
