# Generated by Django 2.2.7 on 2019-11-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitboi_photo', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
