# Generated by Django 2.2.7 on 2019-11-16 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitboi_photo', '0004_recommended_programs_workout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommended_programs',
            old_name='name',
            new_name='recommended_name',
        ),
    ]
